"""initial_schema

Revision ID: 9d02a8b25d99
Revises: 
Create Date: 2026-04-19 15:31:55.747265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d02a8b25d99'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('s3_key_original', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.Column('processing_status', sa.Enum('awaiting_upload', 'uploaded', 'processing', 'ready', 'error', name='fileprocessingstatus'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    op.create_index('idx_files_hash', 'files', ['file_hash'], unique=False, postgresql_using='hash')
    op.create_index('idx_files_status', 'files', ['processing_status'], unique=False)
    op.create_table('permissions',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tariffs',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price_monthly', sa.Numeric(), nullable=False),
    sa.Column('quota_storage_bytes', sa.BigInteger(), nullable=False),
    sa.Column('max_track_duration_sec', sa.Integer(), nullable=False),
    sa.Column('has_api_access', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', 'id')
    )
    op.create_table('users',
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('profile_specialization', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('api_keys',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('webhook_url', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('payments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tariff_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', 'refunded', name='paymentstatus'), nullable=False),
    sa.Column('external_payment_id', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_payment_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('social_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('provider_account_id', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studio_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('exported_file_id', sa.UUID(), nullable=True),
    sa.Column('global_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exported_file_id'], ['files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('following_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'following_id')
    )
    op.create_index('idx_subscriptions_following', 'subscriptions', ['following_id'], unique=False)
    op.create_table('user_quotas_current',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('storage_used_bytes', sa.BigInteger(), nullable=False),
    sa.Column('duration_used_sec', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'id')
    )
    op.create_table('user_subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tariff_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'canceled', 'past_due', 'trialing', name='subscriptionstatus'), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processing_tasks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('model_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', 'canceled', name='taskstatus'), nullable=False),
    sa.Column('celery_task_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_celery_id', 'processing_tasks', ['celery_task_id'], unique=False)
    op.create_index('idx_tasks_status', 'processing_tasks', ['status'], unique=False)
    op.create_index('idx_tasks_status_date', 'processing_tasks', ['status', 'created_at'], unique=False)
    op.create_table('tracks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('source_session_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('visibility', sa.Enum('private', 'public', 'unlisted', name='visibilitystatus'), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('save_count', sa.Integer(), nullable=False),
    sa.Column('downloads_count', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_session_id'], ['studio_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tracks_catalog_filters', 'tracks', ['visibility', 'genre', 'bpm'], unique=False)
    op.create_index('idx_tracks_popularity', 'tracks', ['play_count'], unique=False)
    op.create_index('idx_tracks_search', 'tracks', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('idx_tracks_tags', 'tracks', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('stems',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('stem_class', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('s3_key_flac', sa.String(), nullable=False),
    sa.Column('s3_key_mp3', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['processing_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_physical_stem_unique', 'stems', ['file_id', 'stem_class', 'model_version'], unique=True)
    op.create_index('idx_stems_task', 'stems', ['task_id'], unique=False)
    op.create_table('usage_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('duration_sec_used', sa.Float(), nullable=False),
    sa.Column('storage_bytes_used', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['processing_tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_saved_tracks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_unique_saved_track', 'user_saved_tracks', ['user_id', 'track_id'], unique=True)
    op.create_table('studio_session_tracks',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('stem_id', sa.UUID(), nullable=True),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('track_index', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('pan', sa.Float(), nullable=False),
    sa.Column('is_muted', sa.Boolean(), nullable=False),
    sa.Column('is_solo', sa.Boolean(), nullable=False),
    sa.Column('start_offset_ms', sa.BigInteger(), nullable=False),
    sa.Column('trim_start_ms', sa.BigInteger(), nullable=False),
    sa.Column('trim_end_ms', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(stem_id IS NULL) != (file_id IS NULL)', name='check_stem_or_file'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['studio_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stem_id'], ['stems.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_track_index', 'studio_session_tracks', ['session_id', 'track_index'], unique=True)
    op.create_table('user_stems',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stem_id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=True),
    sa.Column('visibility', sa.Enum('private', 'public', 'unlisted', name='visibilitystatus'), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('downloads_count', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stem_id'], ['stems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_stems_search', 'user_stems', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('idx_user_stems_tags', 'user_stems', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('idx_user_stems_user', 'user_stems', ['user_id'], unique=False)
    op.create_index('idx_user_stems_visibility', 'user_stems', ['visibility'], unique=False)
    op.create_table('activity_feed',
    sa.Column('producer_id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=True),
    sa.Column('user_stem_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('new_release', 'new_stem', 'new_project', name='activitytype'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['producer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['studio_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_stem_id'], ['user_stems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feed_date', 'activity_feed', ['created_at'], unique=False)
    op.create_index('idx_feed_producer', 'activity_feed', ['producer_id'], unique=False)
    op.create_table('user_saved_stems',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_stem_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_stem_id'], ['user_stems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_unique_saved_stem', 'user_saved_stems', ['user_id', 'user_stem_id'], unique=True)
    op.create_table('user_notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity_feed.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_notifications_state', 'user_notifications', ['user_id', 'is_read'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_notifications_state', table_name='user_notifications')
    op.drop_table('user_notifications')
    op.drop_index('idx_unique_saved_stem', table_name='user_saved_stems')
    op.drop_table('user_saved_stems')
    op.drop_index('idx_feed_producer', table_name='activity_feed')
    op.drop_index('idx_feed_date', table_name='activity_feed')
    op.drop_table('activity_feed')
    op.drop_index('idx_user_stems_visibility', table_name='user_stems')
    op.drop_index('idx_user_stems_user', table_name='user_stems')
    op.drop_index('idx_user_stems_tags', table_name='user_stems', postgresql_using='gin')
    op.drop_index('idx_user_stems_search', table_name='user_stems', postgresql_using='gin')
    op.drop_table('user_stems')
    op.drop_index('idx_session_track_index', table_name='studio_session_tracks')
    op.drop_table('studio_session_tracks')
    op.drop_index('idx_unique_saved_track', table_name='user_saved_tracks')
    op.drop_table('user_saved_tracks')
    op.drop_table('usage_logs')
    op.drop_index('idx_stems_task', table_name='stems')
    op.drop_index('idx_physical_stem_unique', table_name='stems')
    op.drop_table('stems')
    op.drop_index('idx_tracks_tags', table_name='tracks', postgresql_using='gin')
    op.drop_index('idx_tracks_search', table_name='tracks', postgresql_using='gin')
    op.drop_index('idx_tracks_popularity', table_name='tracks')
    op.drop_index('idx_tracks_catalog_filters', table_name='tracks')
    op.drop_table('tracks')
    op.drop_index('idx_tasks_status_date', table_name='processing_tasks')
    op.drop_index('idx_tasks_status', table_name='processing_tasks')
    op.drop_index('idx_tasks_celery_id', table_name='processing_tasks')
    op.drop_table('processing_tasks')
    op.drop_table('user_subscriptions')
    op.drop_table('user_quotas_current')
    op.drop_index('idx_subscriptions_following', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('studio_sessions')
    op.drop_table('social_accounts')
    op.drop_table('refresh_tokens')
    op.drop_table('payments')
    op.drop_table('password_reset_tokens')
    op.drop_table('api_keys')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_table('tariffs')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_index('idx_files_status', table_name='files')
    op.drop_index('idx_files_hash', table_name='files', postgresql_using='hash')
    op.drop_table('files')
    # ### end Alembic commands ###
